version: '3.9'
services:
  pta-db-dev:
    container_name: postgres_con
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD : postgres
      POSTGRES_DB: kozidb
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    ports:
      - "5432:5432"
    volumes:
      - ./pta_exposed_config/postgis-custom-config.sh:/docker-entrypoint-initdb.d/postgis-custom-config.sh
      - ./pta_exposed_config/postgis-custom-config.sql:/docker-entrypoint-initdb.d/postgis-custom-config.sql