version: '15.3'
services:
  pta-db-dev:
    container_name: postgres_con
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD : postgres
      POSTGRES_DB: kozidb
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    ports:
      - "5432:5432"
    volumes:
      -  C:\postgres_container_data:/var/lib/postgresql/data
  pta-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pta_img
    ports:
      - "8080:8080"